/// <summary>
/// 디자이너 지원에 필요한 메서드입니다.
/// 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
/// </summary>
#include "InGameHUD.h"

USING_NS_CC;
using namespace cocos2d;
using namespace ui;

InGameHUD * InGameHUD::instance;
InGameHUD::InGameHUD()
{
	root = CSLoader::createNode("InGameHUD.csb");
	this->addChild(root, 0, 1);
	InitPage();
	InGameHUD::instance = this;
}
InGameHUD::InGameHUD(Widget* _root)
{
	root = _root;
	InitPage();
	InGameHUD::instance = this;
}
void InGameHUD::InitPage()
{
	actionInGameHUD = CSLoader::createTimeline("InGameHUD.csb");
	root->runAction(actionInGameHUD);
	Select = actionInGameHUD->getAnimationInfo("Select");
	Deselect = actionInGameHUD->getAnimationInfo("Deselect");
	m_Menu= static_cast<cocos2d::ui::Button* >(root->getChildByName("Menu"));
	m_Menu->retain();
	m_OrderTimebar= static_cast<cocos2d::ui::LoadingBar *>(root->getChildByName("OrderTimebar"));
	m_OrderTimebar->retain();
	m_Button_2_3= static_cast<cocos2d::ui::Button* >(root->getChildByName("Button_2_3"));
	m_Button_2_3->retain();
	m_tbP1mpbar= static_cast<cocos2d::ui::LoadingBar *>(root->getChildByName("tbP1mpbar"));
	m_tbP1mpbar->retain();
	m_tbP1mp= static_cast<cocos2d::ui::Text *>(root->getChildByName("tbP1mp"));
	m_tbP1mp->retain();
	m_tbP2mpbar= static_cast<cocos2d::ui::LoadingBar *>(root->getChildByName("tbP2mpbar"));
	m_tbP2mpbar->retain();
	m_tbP2mp= static_cast<cocos2d::ui::Text *>(root->getChildByName("tbP2mp"));
	m_tbP2mp->retain();
	ListView *_SummonSelctList= static_cast<ListView *>(root->getChildByName("SummonSelctList"));
	_SummonSelctList->retain();
	m_SummonSelctList = new CCInGameHUD::SummonSelctList();
	m_SummonSelctList->root = _SummonSelctList;
	{
		Layout *_Type1= static_cast<Layout *>(_SummonSelctList->getChildByName("Type1"));
		_Type1->retain();
		m_SummonSelctList->m_Type1 = new CCSummonSelctList::Type1();
		m_SummonSelctList->m_Type1->root = _Type1;
		{
			m_SummonSelctList->m_Type1->m_Image_4= static_cast<cocos2d::ui::ImageView *>(_Type1->getChildByName("Image_4"));
			m_SummonSelctList->m_Type1->m_Image_4->retain();
			m_SummonSelctList->m_Type1->m_Chartitle= static_cast<cocos2d::ui::ImageView *>(_Type1->getChildByName("Chartitle"));
			m_SummonSelctList->m_Type1->m_Chartitle->retain();
			m_SummonSelctList->m_Type1->m_Text_3= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3"));
			m_SummonSelctList->m_Type1->m_Text_3->retain();
			m_SummonSelctList->m_Type1->m_Text_3_0= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3_0"));
			m_SummonSelctList->m_Type1->m_Text_3_0->retain();
			m_SummonSelctList->m_Type1->m_Text_3_0_0= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3_0_0"));
			m_SummonSelctList->m_Type1->m_Text_3_0_0->retain();
			m_SummonSelctList->m_Type1->m_Text_3_0_0_0= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3_0_0_0"));
			m_SummonSelctList->m_Type1->m_Text_3_0_0_0->retain();
			m_SummonSelctList->m_Type1->m_Text_3_0_0_1= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3_0_0_1"));
			m_SummonSelctList->m_Type1->m_Text_3_0_0_1->retain();
			m_SummonSelctList->m_Type1->m_Text_3_0_0_1_0= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3_0_0_1_0"));
			m_SummonSelctList->m_Type1->m_Text_3_0_0_1_0->retain();
			m_SummonSelctList->m_Type1->m_Text_3_0_0_1_1= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("Text_3_0_0_1_1"));
			m_SummonSelctList->m_Type1->m_Text_3_0_0_1_1->retain();
			m_SummonSelctList->m_Type1->m_tbMove= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbMove"));
			m_SummonSelctList->m_Type1->m_tbMove->retain();
			m_SummonSelctList->m_Type1->m_tbMP= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbMP"));
			m_SummonSelctList->m_Type1->m_tbMP->retain();
			m_SummonSelctList->m_Type1->m_tbAtk= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbAtk"));
			m_SummonSelctList->m_Type1->m_tbAtk->retain();
			m_SummonSelctList->m_Type1->m_tbInt= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbInt"));
			m_SummonSelctList->m_Type1->m_tbInt->retain();
			m_SummonSelctList->m_Type1->m_tbFeed= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbFeed"));
			m_SummonSelctList->m_Type1->m_tbFeed->retain();
			m_SummonSelctList->m_Type1->m_tbDef= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbDef"));
			m_SummonSelctList->m_Type1->m_tbDef->retain();
			m_SummonSelctList->m_Type1->m_tbRef= static_cast<cocos2d::ui::Text *>(_Type1->getChildByName("tbRef"));
			m_SummonSelctList->m_Type1->m_tbRef->retain();
			m_SummonSelctList->m_Type1->m_Image_6= static_cast<cocos2d::ui::ImageView *>(_Type1->getChildByName("Image_6"));
			m_SummonSelctList->m_Type1->m_Image_6->retain();
			m_SummonSelctList->m_Type1->m_Image_6_0= static_cast<cocos2d::ui::ImageView *>(_Type1->getChildByName("Image_6_0"));
			m_SummonSelctList->m_Type1->m_Image_6_0->retain();
			m_SummonSelctList->m_Type1->m_Image_6_0_0= static_cast<cocos2d::ui::ImageView *>(_Type1->getChildByName("Image_6_0_0"));
			m_SummonSelctList->m_Type1->m_Image_6_0_0->retain();
			m_SummonSelctList->m_Type1->m_Image_6_0_0_0= static_cast<cocos2d::ui::ImageView *>(_Type1->getChildByName("Image_6_0_0_0"));
			m_SummonSelctList->m_Type1->m_Image_6_0_0_0->retain();
			m_SummonSelctList->m_Type1->m_Conneritem2_5= static_cast<cocos2d::Sprite *>(_Type1->getChildByName("Conneritem2_5"));
			m_SummonSelctList->m_Type1->m_Conneritem2_5->retain();
			m_SummonSelctList->m_Type1->m_Conneritem2_5_0= static_cast<cocos2d::Sprite *>(_Type1->getChildByName("Conneritem2_5_0"));
			m_SummonSelctList->m_Type1->m_Conneritem2_5_0->retain();
			m_SummonSelctList->m_Type1->m_Conneritem4_7= static_cast<cocos2d::Sprite *>(_Type1->getChildByName("Conneritem4_7"));
			m_SummonSelctList->m_Type1->m_Conneritem4_7->retain();
			m_SummonSelctList->m_Type1->m_Button_1= static_cast<cocos2d::ui::Button* >(_Type1->getChildByName("Button_1"));
			m_SummonSelctList->m_Type1->m_Button_1->retain();
		}
		Layout *_Type2= static_cast<Layout *>(_SummonSelctList->getChildByName("Type2"));
		_Type2->retain();
		m_SummonSelctList->m_Type2 = new CCSummonSelctList::Type2();
		m_SummonSelctList->m_Type2->root = _Type2;
		{
			m_SummonSelctList->m_Type2->m_Image_4= static_cast<cocos2d::ui::ImageView *>(_Type2->getChildByName("Image_4"));
			m_SummonSelctList->m_Type2->m_Image_4->retain();
			m_SummonSelctList->m_Type2->m_Chartitle= static_cast<cocos2d::ui::ImageView *>(_Type2->getChildByName("Chartitle"));
			m_SummonSelctList->m_Type2->m_Chartitle->retain();
			m_SummonSelctList->m_Type2->m_Text_3= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3"));
			m_SummonSelctList->m_Type2->m_Text_3->retain();
			m_SummonSelctList->m_Type2->m_Text_3_0= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3_0"));
			m_SummonSelctList->m_Type2->m_Text_3_0->retain();
			m_SummonSelctList->m_Type2->m_Text_3_0_0= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3_0_0"));
			m_SummonSelctList->m_Type2->m_Text_3_0_0->retain();
			m_SummonSelctList->m_Type2->m_Text_3_0_0_0= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3_0_0_0"));
			m_SummonSelctList->m_Type2->m_Text_3_0_0_0->retain();
			m_SummonSelctList->m_Type2->m_Text_3_0_0_1= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3_0_0_1"));
			m_SummonSelctList->m_Type2->m_Text_3_0_0_1->retain();
			m_SummonSelctList->m_Type2->m_Text_3_0_0_1_0= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3_0_0_1_0"));
			m_SummonSelctList->m_Type2->m_Text_3_0_0_1_0->retain();
			m_SummonSelctList->m_Type2->m_Text_3_0_0_1_1= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("Text_3_0_0_1_1"));
			m_SummonSelctList->m_Type2->m_Text_3_0_0_1_1->retain();
			m_SummonSelctList->m_Type2->m_tbMove= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbMove"));
			m_SummonSelctList->m_Type2->m_tbMove->retain();
			m_SummonSelctList->m_Type2->m_tbMP= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbMP"));
			m_SummonSelctList->m_Type2->m_tbMP->retain();
			m_SummonSelctList->m_Type2->m_tbAtk= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbAtk"));
			m_SummonSelctList->m_Type2->m_tbAtk->retain();
			m_SummonSelctList->m_Type2->m_tbInt= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbInt"));
			m_SummonSelctList->m_Type2->m_tbInt->retain();
			m_SummonSelctList->m_Type2->m_tbFeed= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbFeed"));
			m_SummonSelctList->m_Type2->m_tbFeed->retain();
			m_SummonSelctList->m_Type2->m_tbDef= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbDef"));
			m_SummonSelctList->m_Type2->m_tbDef->retain();
			m_SummonSelctList->m_Type2->m_tbRef= static_cast<cocos2d::ui::Text *>(_Type2->getChildByName("tbRef"));
			m_SummonSelctList->m_Type2->m_tbRef->retain();
			m_SummonSelctList->m_Type2->m_Image_6= static_cast<cocos2d::ui::ImageView *>(_Type2->getChildByName("Image_6"));
			m_SummonSelctList->m_Type2->m_Image_6->retain();
			m_SummonSelctList->m_Type2->m_Image_6_0= static_cast<cocos2d::ui::ImageView *>(_Type2->getChildByName("Image_6_0"));
			m_SummonSelctList->m_Type2->m_Image_6_0->retain();
			m_SummonSelctList->m_Type2->m_Image_6_0_0= static_cast<cocos2d::ui::ImageView *>(_Type2->getChildByName("Image_6_0_0"));
			m_SummonSelctList->m_Type2->m_Image_6_0_0->retain();
			m_SummonSelctList->m_Type2->m_Image_6_0_0_0= static_cast<cocos2d::ui::ImageView *>(_Type2->getChildByName("Image_6_0_0_0"));
			m_SummonSelctList->m_Type2->m_Image_6_0_0_0->retain();
			m_SummonSelctList->m_Type2->m_Conneritem2_5= static_cast<cocos2d::Sprite *>(_Type2->getChildByName("Conneritem2_5"));
			m_SummonSelctList->m_Type2->m_Conneritem2_5->retain();
			m_SummonSelctList->m_Type2->m_Conneritem2_5_0= static_cast<cocos2d::Sprite *>(_Type2->getChildByName("Conneritem2_5_0"));
			m_SummonSelctList->m_Type2->m_Conneritem2_5_0->retain();
			m_SummonSelctList->m_Type2->m_Conneritem4_7= static_cast<cocos2d::Sprite *>(_Type2->getChildByName("Conneritem4_7"));
			m_SummonSelctList->m_Type2->m_Conneritem4_7->retain();
			m_SummonSelctList->m_Type2->m_Button_1= static_cast<cocos2d::ui::Button* >(_Type2->getChildByName("Button_1"));
			m_SummonSelctList->m_Type2->m_Button_1->retain();
		}
		Layout *_Panel_1_1= static_cast<Layout *>(_SummonSelctList->getChildByName("Panel_1_1"));
		_Panel_1_1->retain();
		m_SummonSelctList->m_Panel_1_1 = new CCSummonSelctList::Panel_1_1();
		m_SummonSelctList->m_Panel_1_1->root = _Panel_1_1;
		{
			m_SummonSelctList->m_Panel_1_1->m_Image_4= static_cast<cocos2d::ui::ImageView *>(_Panel_1_1->getChildByName("Image_4"));
			m_SummonSelctList->m_Panel_1_1->m_Image_4->retain();
			m_SummonSelctList->m_Panel_1_1->m_Chartitle= static_cast<cocos2d::ui::ImageView *>(_Panel_1_1->getChildByName("Chartitle"));
			m_SummonSelctList->m_Panel_1_1->m_Chartitle->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3_0"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3_0_0"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_0= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3_0_0_0"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_1= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3_0_0_1"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_1->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_1_0= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3_0_0_1_0"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_1_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_1_1= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("Text_3_0_0_1_1"));
			m_SummonSelctList->m_Panel_1_1->m_Text_3_0_0_1_1->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbMove= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbMove"));
			m_SummonSelctList->m_Panel_1_1->m_tbMove->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbMP= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbMP"));
			m_SummonSelctList->m_Panel_1_1->m_tbMP->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbAtk= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbAtk"));
			m_SummonSelctList->m_Panel_1_1->m_tbAtk->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbInt= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbInt"));
			m_SummonSelctList->m_Panel_1_1->m_tbInt->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbFeed= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbFeed"));
			m_SummonSelctList->m_Panel_1_1->m_tbFeed->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbDef= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbDef"));
			m_SummonSelctList->m_Panel_1_1->m_tbDef->retain();
			m_SummonSelctList->m_Panel_1_1->m_tbRef= static_cast<cocos2d::ui::Text *>(_Panel_1_1->getChildByName("tbRef"));
			m_SummonSelctList->m_Panel_1_1->m_tbRef->retain();
			m_SummonSelctList->m_Panel_1_1->m_Image_6= static_cast<cocos2d::ui::ImageView *>(_Panel_1_1->getChildByName("Image_6"));
			m_SummonSelctList->m_Panel_1_1->m_Image_6->retain();
			m_SummonSelctList->m_Panel_1_1->m_Image_6_0= static_cast<cocos2d::ui::ImageView *>(_Panel_1_1->getChildByName("Image_6_0"));
			m_SummonSelctList->m_Panel_1_1->m_Image_6_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Image_6_0_0= static_cast<cocos2d::ui::ImageView *>(_Panel_1_1->getChildByName("Image_6_0_0"));
			m_SummonSelctList->m_Panel_1_1->m_Image_6_0_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Image_6_0_0_0= static_cast<cocos2d::ui::ImageView *>(_Panel_1_1->getChildByName("Image_6_0_0_0"));
			m_SummonSelctList->m_Panel_1_1->m_Image_6_0_0_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Conneritem2_5= static_cast<cocos2d::Sprite *>(_Panel_1_1->getChildByName("Conneritem2_5"));
			m_SummonSelctList->m_Panel_1_1->m_Conneritem2_5->retain();
			m_SummonSelctList->m_Panel_1_1->m_Conneritem2_5_0= static_cast<cocos2d::Sprite *>(_Panel_1_1->getChildByName("Conneritem2_5_0"));
			m_SummonSelctList->m_Panel_1_1->m_Conneritem2_5_0->retain();
			m_SummonSelctList->m_Panel_1_1->m_Conneritem4_7= static_cast<cocos2d::Sprite *>(_Panel_1_1->getChildByName("Conneritem4_7"));
			m_SummonSelctList->m_Panel_1_1->m_Conneritem4_7->retain();
			m_SummonSelctList->m_Panel_1_1->m_Button_1= static_cast<cocos2d::ui::Button* >(_Panel_1_1->getChildByName("Button_1"));
			m_SummonSelctList->m_Panel_1_1->m_Button_1->retain();
		}
		Layout *_Panel_1_2= static_cast<Layout *>(_SummonSelctList->getChildByName("Panel_1_2"));
		_Panel_1_2->retain();
		m_SummonSelctList->m_Panel_1_2 = new CCSummonSelctList::Panel_1_2();
		m_SummonSelctList->m_Panel_1_2->root = _Panel_1_2;
		{
			m_SummonSelctList->m_Panel_1_2->m_Image_4= static_cast<cocos2d::ui::ImageView *>(_Panel_1_2->getChildByName("Image_4"));
			m_SummonSelctList->m_Panel_1_2->m_Image_4->retain();
			m_SummonSelctList->m_Panel_1_2->m_Chartitle= static_cast<cocos2d::ui::ImageView *>(_Panel_1_2->getChildByName("Chartitle"));
			m_SummonSelctList->m_Panel_1_2->m_Chartitle->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3_0"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3_0_0"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_0= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3_0_0_0"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_1= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3_0_0_1"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_1->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_1_0= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3_0_0_1_0"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_1_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_1_1= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("Text_3_0_0_1_1"));
			m_SummonSelctList->m_Panel_1_2->m_Text_3_0_0_1_1->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbMove= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbMove"));
			m_SummonSelctList->m_Panel_1_2->m_tbMove->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbMP= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbMP"));
			m_SummonSelctList->m_Panel_1_2->m_tbMP->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbAtk= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbAtk"));
			m_SummonSelctList->m_Panel_1_2->m_tbAtk->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbInt= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbInt"));
			m_SummonSelctList->m_Panel_1_2->m_tbInt->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbFeed= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbFeed"));
			m_SummonSelctList->m_Panel_1_2->m_tbFeed->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbDef= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbDef"));
			m_SummonSelctList->m_Panel_1_2->m_tbDef->retain();
			m_SummonSelctList->m_Panel_1_2->m_tbRef= static_cast<cocos2d::ui::Text *>(_Panel_1_2->getChildByName("tbRef"));
			m_SummonSelctList->m_Panel_1_2->m_tbRef->retain();
			m_SummonSelctList->m_Panel_1_2->m_Image_6= static_cast<cocos2d::ui::ImageView *>(_Panel_1_2->getChildByName("Image_6"));
			m_SummonSelctList->m_Panel_1_2->m_Image_6->retain();
			m_SummonSelctList->m_Panel_1_2->m_Image_6_0= static_cast<cocos2d::ui::ImageView *>(_Panel_1_2->getChildByName("Image_6_0"));
			m_SummonSelctList->m_Panel_1_2->m_Image_6_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Image_6_0_0= static_cast<cocos2d::ui::ImageView *>(_Panel_1_2->getChildByName("Image_6_0_0"));
			m_SummonSelctList->m_Panel_1_2->m_Image_6_0_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Image_6_0_0_0= static_cast<cocos2d::ui::ImageView *>(_Panel_1_2->getChildByName("Image_6_0_0_0"));
			m_SummonSelctList->m_Panel_1_2->m_Image_6_0_0_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Conneritem2_5= static_cast<cocos2d::Sprite *>(_Panel_1_2->getChildByName("Conneritem2_5"));
			m_SummonSelctList->m_Panel_1_2->m_Conneritem2_5->retain();
			m_SummonSelctList->m_Panel_1_2->m_Conneritem2_5_0= static_cast<cocos2d::Sprite *>(_Panel_1_2->getChildByName("Conneritem2_5_0"));
			m_SummonSelctList->m_Panel_1_2->m_Conneritem2_5_0->retain();
			m_SummonSelctList->m_Panel_1_2->m_Conneritem4_7= static_cast<cocos2d::Sprite *>(_Panel_1_2->getChildByName("Conneritem4_7"));
			m_SummonSelctList->m_Panel_1_2->m_Conneritem4_7->retain();
			m_SummonSelctList->m_Panel_1_2->m_Button_1= static_cast<cocos2d::ui::Button* >(_Panel_1_2->getChildByName("Button_1"));
			m_SummonSelctList->m_Panel_1_2->m_Button_1->retain();
		}
	}
	m_Char1= static_cast<cocos2d::Sprite *>(root->getChildByName("Char1"));
	m_Char1->retain();
	m_Char2= static_cast<cocos2d::Sprite *>(root->getChildByName("Char2"));
	m_Char2->retain();
	m_tbPlayer1= static_cast<cocos2d::ui::Text *>(root->getChildByName("tbPlayer1"));
	m_tbPlayer1->retain();
	m_tbPlayer2= static_cast<cocos2d::ui::Text *>(root->getChildByName("tbPlayer2"));
	m_tbPlayer2->retain();
	m_Player1Hpbar= static_cast<cocos2d::ui::LoadingBar *>(root->getChildByName("Player1Hpbar"));
	m_Player1Hpbar->retain();
	m_Player2Hpbar= static_cast<cocos2d::ui::LoadingBar *>(root->getChildByName("Player2Hpbar"));
	m_Player2Hpbar->retain();
	m_tbP2hp= static_cast<cocos2d::ui::Text *>(root->getChildByName("tbP2hp"));
	m_tbP2hp->retain();
	m_tbP1hp= static_cast<cocos2d::ui::Text *>(root->getChildByName("tbP1hp"));
	m_tbP1hp->retain();
	m_MoveButton= static_cast<cocos2d::ui::Button* >(root->getChildByName("MoveButton"));
	m_MoveButton->retain();
	m_MagicButton= static_cast<cocos2d::ui::Button* >(root->getChildByName("MagicButton"));
	m_MagicButton->retain();
	m_SummonButton= static_cast<cocos2d::ui::Button* >(root->getChildByName("SummonButton"));
	m_SummonButton->retain();
}
